### ISSUE TITLE
identical users with command line superuser creation 

### ISSUE THREAD

**Issue by Bassbiest** [rdmorganiser/rdmo#111] opened 2019-02-05 15:07 UTC
## steps to recreate
* conditions: first installation of rdmo on a new virtual environment (not checked with fully operational instance)
* create a superuser from command line "python manage.py createsuperuser" (use default name)
* create another superuser from command line with the same name (I used the same name with first letter in uppercase)
* login on the running server will fail (Debug screen message: get function returns two entries instead of one)

## expected behaviour
When creating a new superuser with the same name the user should be warned and maybe asked if the existing user should be overwritten

## actual behaviour
There is no indication a user with the same name already exists and the program adds the new user to the list which leads to a login fail for both users.

### further information
OS: Win 10 
up to date branch

**Comment by triole** [comment] 2019-02-06 10:17
I was not able to reproduce this behaviour. I tried using PostgreSQL and SQLite databases. In both cases user names were dealt with in a case sensitive manner. When I tried creating a user that already existed I got an error message saying that the username was already taken.

Here is what I did:

1. created a fresh installlation of RDMO
2. created a super user called `peter`
3. created a super user called `Peter`
4. successfully logged in with `peter`
5. successfully logged in with `Peter`

Did I miss anything? Did your user have special names? Which database are you using? Which Python version do you have?

**Comment by Bassbiest** [comment] 2019-02-07 09:37
Upon recreating it myself I noticed that another component seems to be involved. I used a password manager (Keepass) to paste the password into the command line. Although the password on the debug screen and the one I wanted to use are identical (32 characters consisting of upper-, lowercase letters and numbers) this seems to cause trouble as I do not get the error when just typing it into the command line. However, both users get corrupted when the bug occours.

I attached part of the debug screen this time. Also all my settings fall back to default values as I didn't get around to modify the local.py file except for the debug option. 

![debug_screen](https://user-images.githubusercontent.com/30717374/52402354-56d0ec80-2ac4-11e9-9c23-6fbd5dadcd1e.png)

**Comment by triole** [comment] 2019-02-07 10:36
This problem seems to be a tough one because Keepass and copy and paste into the shell is involved. There are certainly some issues when trying to copy and paste into the linux terminal. Depending on what terminal you use it is not recommended to try it at all. Others say that STRG-SHIFT-INSERT instead of STRG-SHIFT-V does work. 

I myself use KeepassXC and was not able to reproduce pasting into the xfce4-terminal. I will try to investigate further but do have the impression that the problem is nothing to be fixed on the RDMO side. Nonetheless it would be interesting to find out what exactly happens.

**Closed** 2019-02-22 10:03 UTC
