### ISSUE TITLE
Exported "options.xml" cannot be imported again

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#575] opened 2023-01-31 09:12 UTC
### Description / Beschreibung

An "options.xml" file exported by a RDMO instance is not accepted by the same instance as a valid source file.

That happens only for options, not for questions catalogues.

### Steps to reproduce / Schritte zum Reproduzieren

1. Go to [https://](https://rdmocat.aip.de/options/)
2. Click on 'Export / XML'
3. Save the XML file 
4. Click on 'Import' / 'Select file' / blue arrow
5. Click on 'Import elements'
6. You get the error message "Bad request"
7. Even if you click on 'Cancel', you get the same error message.

![image](https://user-images.githubusercontent.com/37865804/215717097-bff06c3d-3c17-41f6-aef9-98fc80a6de2c.png)

**Comment by jochenklar** [comment] 2023-02-02 09:47
Hey @Zack-83 , at least for our test files it works as intended, can you send me the options.xml you want to import, either here or by mail?

**Comment by Zack-83** [comment] 2023-02-02 13:14
Gerne, Jochen! Anbei zwei Dateien.

Danke für die Unterstützung!

P. S. Beim Herunterladen wird die Datei "options.xml" benannt, im 
Repositorium heißt sie aber "rdmo.xml": das ruft auch nach Harmonisierung.

Viele Grüße
Giacomo



Von:    "Jochen Klar" ***@***.***>
An:     "rdmorganiser/rdmo" ***@***.***>
Kopie:  "Giacomo Lanza" ***@***.***>, "Mention" 
***@***.***>
Datum:  02.02.2023 10:47
Betreff:        Re: [rdmorganiser/rdmo] Exported "options.xml" cannot be 
imported again (Issue #575)



Hey @Zack-83 , at least for our test files it works as intended, can you 
send me the options.xml you want to import, either here or by mail?
?
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by triole** [comment] 2023-02-03 13:07
I increased the max setting so that imports should work again. For the options that were causing the problem it is fine now.

**Comment by triole** [comment] 2023-02-03 13:08
Closing the issue.

**Closed by triole** 2023-02-03 13:08 UTC
Labels: type: bug

**Comment by Zack-83** [comment] 2023-02-03 15:01
Danke, Jungs 👐
