### ISSUE TITLE
Project creation via API allows for projects without catalog

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#674] opened 2023-08-17 08:58 UTC
### Rationale / Begründung

We found projects without catalog in our instance.
Project creation should raise a validation error when leaving the catalog empty.

### Affected 

API-Users

### Minimal functionality

* a validation error should be given when catalogs is `null` 

### References / Verweise

* POST to `/api/v1/projects/projects/" `
* https://github.com/rdmorganiser/rdmo/issues/593

**Comment by jochenklar** [comment] 2023-08-18 12:43
The problem is that the catalog in the `Project` model can be `None`, e.g. when the catalog was deleted. I fixed the serializer to correctly validate the catalog field and also check for catalog availability.

**Comment by jochenklar** [comment] 2023-10-04 06:42
Fixed in https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0

**Closed by jochenklar** 2023-10-04 06:42 UTC
Labels: type:bug
